version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - BASE_URL_PORT=5000
      - MYSQL_ROOT_PASSWORD=s3k0l4hd3v0p5
      - DATABASE_USERNAME=people
      - DATABASE_PASSWORD=people
      - DATABASE_DATABASE=people
      - DATABASE_HOST=cilist-db
      - DATABASE_PORT=3306

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://BACKEND_PUBLIC_IP:5000
