version: '3.8'

services:
  database:
    container_name: cilist-db
    build:
      context: ./database
    restart: "on-failure"
    healthcheck:
      test: ["CMD-SHELL", "test -d '/var/lib/mysql/people'"]
      interval: 5s  # the command will be run every 5 seconds
      timeout: 3s   # maximum time for test to run before considered failure
      retries: 10   # number of retried before considered failure
  
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - BASE_URL_PORT=5000
      - MYSQL_ROOT_PASSWORD=s3k0l4hd3v0p5
      - DATABASE_USERNAME=people
      - DATABASE_PASSWORD=people
      - DATABASE_DATABASE=people
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
    depends_on:
      database:
        condition: service_healthy
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://BACKEND_PUBLIC_IP:5000
    depends_on:
      backend:
        condition: service_healthy
